# Generated by Django 5.1.2 on 2024-11-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
    ]
