# Generated by Django 5.1.2 on 2024-10-28 11:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_remove_product_image_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
