# Generated by Django 5.1.2 on 2024-11-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_category_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
