# Generated by Django 5.1.2 on 2024-10-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
