# Generated by Django 5.1.2 on 2024-11-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_product_specifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="products/"),
        ),
    ]
