# Generated by Django 5.1.2 on 2024-10-29 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_category_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
