# Generated by Django 5.1.2 on 2024-11-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_remove_product_specifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ratings_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="reviews_count",
            field=models.IntegerField(default=0),
        ),
    ]
