# Generated by Django 5.1.2 on 2024-11-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_order_updated_at_orderitem_price_at_purchase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
