# Generated by Django 5.1.2 on 2024-10-31 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_alter_product_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
