# Generated by Django 5.1.2 on 2024-12-24 07:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_alter_orderitem_order"),
        ("shop", "0012_remove_product_category_delete_category"),
    ]

    operations = []
